// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoToDoList.data;

#nullable disable

namespace ProjetoToDoList.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20251123175014_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProjetoToDoList.models.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Observção")
                        .HasColumnType("longtext");

                    b.Property<string>("Tarefas")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DBT");
                });
#pragma warning restore 612, 618
        }
    }
}
